version: '3'
services:

  # The Application
  app:
    image: hieuleader/laravel-app
    working_dir: /var/www
    volumes:
      - /var/www/storage
    environment:
      - "DB_HOST=database"
      - "REDIS_HOST=cache"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    tty: true
    ports:
      - "9000:9000"
  web:
    image: hieuleader/laravel-web
    ports:
      - 80:80
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    depends_on:
      - app
  database:
    image: mysql:latest
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=laravel"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=hieu"
      - "MYSQL_ROOT_PASSWORD=hieu"
    ports:
        - "33061:3306"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: 10
  cache:
    image: redis:3.0-alpine
volumes:
  dbdata: